### ISSUE TITLE
apply_template creates a VS but does not apply a template

### ISSUE THREAD

**Issue by matthew-hickok** [KEMPtechnologies/python-kemptech-api#4] opened 2017-04-07 15:33 UTC
I've been unable to apply a template to a virtual service. 

lm.apply_template("10.0.3.84", 443, "tcp", "Skype Front End Reverse Proxy")

Doing that results in a new vs being created, but it is not created with the appropriate template applied. 

No errors are thrown.

**Comment by lawnmowerlatte** [comment] 2017-04-13 20:24
@matthew-hickok, I was able to reproduce the problem and identify the cause. The wrong parameter is passed to the API. I've patched it and the fix will be in the next release.

**Closed by lawnmowerlatte** 2017-04-13 20:24 UTC

**Comment by Dannyzen** [comment] 2017-04-20 15:31
Fixed in [Release 0.7.27](https://github.com/KEMPtechnologies/python-kemptech-api/releases/tag/0.7.27)
